services:
  db:
    build: ./docker/db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}

    ports:
      - 5433:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8008:${PORT}